import {
  CommonEnableDisable,
  CommonEnableDisables,
} from "../../../../common/common-types";

/**
 * FortiOS IPv4 firewall address group configuration for enterprise network security.
 *
 * Supports up to 600 IPv4 address objects per group with hardware-accelerated evaluation,
 * exclusion logic for complex policies, Security Fabric global distribution, Zero Trust
 * Network Access integration with EMS and geographic tags, and enterprise-grade management.
 *
 * @example
 * ```typescript
 * const group: FortiOSFirewallAddrGrp = {
 *   name: 'enterprise-datacenter-services',
 *   type: FortiOSFirewallAddrGrpType.Default,
 *   member: [{ name: 'web-cluster' }, { name: 'db-cluster' }],
 *   comment: 'Enterprise datacenter services',
 *   exclude: CommonEnableDisable.Enable,
 *   'exclude-member': [{ name: 'dmz-servers' }],
 *   color: 3,
 *   'fabric-object': CommonEnableDisable.Enable,
 *   'allow-routing': CommonEnableDisable.Enable,
 *   category: FortiOSFirewallAddrGrpCategory.Default,
 *   tagging: [{ name: 'Production', category: 'Environment', tags: [{ name: 'Critical' }] }],
 *   uuid: '550e8400-e29b-41d4-a716-446655440000'
 * };
 * ```
 */
export interface FortiOSFirewallAddrGrp {
  /**
   * Unique name identifier for the IPv4 address group within the FortiGate configuration.
   * @maxLength 79
   * @required
   */
  name: string;

  /**
   * IPv4 address group type classification controlling membership behavior and organizational structure.
   * @see FortiOSFirewallAddrGrpType
   * @optional
   */
  type?: FortiOSFirewallAddrGrpTypes | FortiOSFirewallAddrGrpType;

  /**
   * IPv4 address group category for ZTNA and advanced policy integration with EMS and geographic tags.
   * @see FortiOSFirewallAddrGrpCategory
   * @optional
   */
  category?: FortiOSFirewallAddrGrpCategories | FortiOSFirewallAddrGrpCategory;

  /**
   * Universally unique identifier for the IPv4 address group automatically generated by FortiOS.
   * @readonly
   * @optional
   */
  readonly uuid?: string;

  /**
   * Enable IPv4 route advertisement for address group members in dynamic routing protocols.
   * @values "enable" | "disable"
   * @optional
   */
  "allow-routing"?: CommonEnableDisables | CommonEnableDisable;

  /**
   * IPv4 address objects contained within the group supporting up to 600 members with enterprise validation.
   * @maxItems 600
   * @required
   */
  member: {
    /**
     * IPv4 address object name reference that must exist in the same VDOM or global scope.
     * @maxLength 79
     * @required
     */
    name: string;
  }[];

  /**
   * Administrative comment for IPv4 address group documentation and enterprise configuration management.
   * @maxLength 255
   * @optional
   */
  comment?: string;

  /**
   * Enable exclusion logic for advanced IPv4 address group filtering and complex network policies.
   * @values "enable" | "disable"
   * @optional
   */
  exclude?: CommonEnableDisables | CommonEnableDisable;

  /**
   * IPv4 address exclusion members for advanced filtering when exclusion logic is enabled.
   * @requires exclude must be enabled
   * @optional
   */
  "exclude-member"?: {
    /**
     * IPv4 address object name for exclusion that must reference an existing address object.
     * @maxLength 79
     * @optional
     */
    name?: string;
  }[];

  /**
   * GUI color identifier for visual IPv4 address group management and organization in FortiGate interfaces.
   * @minimum 0
   * @maximum 32
   * @optional
   */
  color?: number;

  /**
   * Metadata tagging system for IPv4 address group classification with hierarchical organization support.
   * @optional
   */
  tagging?: {
    /**
     * Descriptive name for the tagging entry grouping providing human-readable identification.
     * @maxLength 63
     * @optional
     */
    name?: string;

    /**
     * Tag category for organizational hierarchy and structured tag management filtering.
     * @maxLength 63
     * @optional
     */
    category?: string;

    /**
     * Collection of individual tags within the category for detailed classification metadata.
     * @required
     */
    tags: {
      /**
       * Individual tag name providing specific classification detail following organizational conventions.
       * @maxLength 79
       * @optional
       */
      name?: string;
    }[];
  }[];

  /**
   * Security Fabric global object distribution control for IPv4 address group synchronization across devices.
   * @values "enable" | "disable"
   * @optional
   */
  "fabric-object"?: CommonEnableDisables | CommonEnableDisable;
}

// FortiOS IPv4 address group type enumeration for organizational control
export enum FortiOSFirewallAddrGrpType {
  // Default IPv4 address group type allowing flexible membership for complex network policies
  Default = "default",
  // Folder IPv4 address group type enforcing exclusive membership for compliance environments
  Folder = "folder",
}

// FortiOS IPv4 address group type union for flexible typing
export type FortiOSFirewallAddrGrpTypes = "default" | "folder";

// FortiOS IPv4 address group category enumeration for ZTNA and policy integration
export enum FortiOSFirewallAddrGrpCategory {
  // Default IPv4 address group category for traditional policies without ZTNA capabilities
  Default = "default",
  // ZTNA EMS tag category for endpoint compliance-based policies requiring EMS tag members
  "Ztna-Ems-Tag" = "ztna-ems-tag",
  // ZTNA geographic tag category for location-based access control requiring geographic members
  "Ztna-Geo-Tag" = "ztna-geo-tag",
}

// FortiOS IPv4 address group category union for flexible typing
export type FortiOSFirewallAddrGrpCategories =
  | "default"
  | "ztna-ems-tag"
  | "ztna-geo-tag";
