/**
 * DataScript configuration for AVI Virtual Service.
 * Contains event type and script content.
 * @interface
 * @example
 * ```typescript
 * const script: VMwareAVIVSDataScript = {
 *   evt: VMwareAVIVSDataScriptType.VS_DATASCRIPT_EVT_HTTP_REQ,
 *   script: 'avi.http.method()'
 * };
 * ```
 */
export interface VMwareAVIVSDataScript {
  /** Event type that triggers the script */
  evt: VMwareAVIVSDataScriptTypes | VMwareAVIVSDataScriptType;
  /** Lua script content */
  script: string;
}

// DataScript event types for AVI Virtual Services
export enum VMwareAVIVSDataScriptType {
  VS_DATASCRIPT_EVT_HTTP_REQ = "VS_DATASCRIPT_EVT_HTTP_REQ",
  VS_DATASCRIPT_EVT_HTTP_RESP = "VS_DATASCRIPT_EVT_HTTP_RESP",
  VS_DATASCRIPT_EVT_HTTP_RESP_DATA = "VS_DATASCRIPT_EVT_HTTP_RESP_DATA",
  VS_DATASCRIPT_EVT_HTTP_LB_FAILED = "VS_DATASCRIPT_EVT_HTTP_LB_FAILED",
  VS_DATASCRIPT_EVT_HTTP_REQ_DATA = "VS_DATASCRIPT_EVT_HTTP_REQ_DATA",
  VS_DATASCRIPT_EVT_HTTP_RESP_FAILED = "VS_DATASCRIPT_EVT_HTTP_RESP_FAILED",
  VS_DATASCRIPT_EVT_HTTP_LB_DONE = "VS_DATASCRIPT_EVT_HTTP_LB_DONE",
  VS_DATASCRIPT_EVT_HTTP_AUTH = "VS_DATASCRIPT_EVT_HTTP_AUTH",
  VS_DATASCRIPT_EVT_HTTP_POST_AUTH = "VS_DATASCRIPT_EVT_HTTP_POST_AUTH",
  VS_DATASCRIPT_EVT_TCP_CLIENT_ACCEPT = "VS_DATASCRIPT_EVT_TCP_CLIENT_ACCEPT",
  VS_DATASCRIPT_EVT_SSL_HANDSHAKE_DONE = "VS_DATASCRIPT_EVT_SSL_HANDSHAKE_DONE",
  VS_DATASCRIPT_EVT_CLIENT_SSL_PRE_CONNECT =
    "VS_DATASCRIPT_EVT_CLIENT_SSL_PRE_CONNECT",
  VS_DATASCRIPT_EVT_CLIENT_SSL_CLIENT_HELLO =
    "VS_DATASCRIPT_EVT_CLIENT_SSL_CLIENT_HELLO",
  VS_DATASCRIPT_EVT_DNS_REQ = "VS_DATASCRIPT_EVT_DNS_REQ",
  VS_DATASCRIPT_EVT_DNS_RESP = "VS_DATASCRIPT_EVT_DNS_RESP",
  VS_DATASCRIPT_EVT_L4_REQUEST = "VS_DATASCRIPT_EVT_L4_REQUEST",
  VS_DATASCRIPT_EVT_L4_RESPONSE = "VS_DATASCRIPT_EVT_L4_RESPONSE",
  VS_DATASCRIPT_EVT_MAX = "VS_DATASCRIPT_EVT_MAX",
}

// Union type of all DataScript event types
export type VMwareAVIVSDataScriptTypes =
  | "VS_DATASCRIPT_EVT_HTTP_REQ"
  | "VS_DATASCRIPT_EVT_HTTP_RESP"
  | "VS_DATASCRIPT_EVT_HTTP_RESP_DATA"
  | "VS_DATASCRIPT_EVT_HTTP_LB_FAILED"
  | "VS_DATASCRIPT_EVT_HTTP_REQ_DATA"
  | "VS_DATASCRIPT_EVT_HTTP_RESP_FAILED"
  | "VS_DATASCRIPT_EVT_HTTP_LB_DONE"
  | "VS_DATASCRIPT_EVT_HTTP_AUTH"
  | "VS_DATASCRIPT_EVT_HTTP_POST_AUTH"
  | "VS_DATASCRIPT_EVT_TCP_CLIENT_ACCEPT"
  | "VS_DATASCRIPT_EVT_SSL_HANDSHAKE_DONE"
  | "VS_DATASCRIPT_EVT_CLIENT_SSL_PRE_CONNECT"
  | "VS_DATASCRIPT_EVT_CLIENT_SSL_CLIENT_HELLO"
  | "VS_DATASCRIPT_EVT_DNS_REQ"
  | "VS_DATASCRIPT_EVT_DNS_RESP"
  | "VS_DATASCRIPT_EVT_L4_REQUEST"
  | "VS_DATASCRIPT_EVT_L4_RESPONSE"
  | "VS_DATASCRIPT_EVT_MAX";
